### ISSUE TITLE
Article show page throws error when related articles are Nil

### ISSUE THREAD

**Issue by partydrone** [wavetronix/glados#107]
# ActionView::MissingTemplate in CaseStudies#show
Showing /srv/www/glados/releases/20170328180050/app/views/articles/show.html.erb where line #106 raised:

Missing partial case_studies/_related_nil_class, application/_related_nil_class with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}. Searched in:
  * "/srv/www/glados/releases/20170328180050/app/views"
  * "/home/deploy/.bundler/glados/ruby/2.3.0/gems/foundation-rails-6.2.4.0/app/views"
  * "/home/deploy/.bundler/glados/ruby/2.3.0/gems/ckeditor-4.2.2/app/views"

Extracted source (around line #106):
```
104      </div>
105      <% MarketingContentFilter.new(@article.related).filter.shift(3).each do |object| %>
106        <%= render partial: "related_#{object.class.to_s.underscore}", object: object %>
107      <% end %>
108    </div>
109  </aside>
```

Rails.root: /srv/www/glados/releases/20170328180050

Application Trace | Framework Trace | Full Trace
app/views/articles/show.html.erb:106:in `block in _app_views_articles_show_html_erb___2963199015606217737_100471520'
app/views/articles/show.html.erb:105:in `each'
app/views/articles/show.html.erb:105:in `_app_views_articles_show_html_erb___2963199015606217737_100471520'
app/controllers/case_studies_controller.rb:6:in `show'

## Request

Parameters:

{"locale"=>"en", "id"=>"1-intersection-advance-warning-system"}

## Response

Headers:

None

**Comment by ehuntsman** [comment]
also removed the "related articles" if there is none.

**Comment by partydrone** [comment]
Looks like this is still an issue.
