### ISSUE TITLE
Make offsite links open a new tab

### ISSUE THREAD

**Issue by partydrone** [wavetronix/glados#130]
- [x] SmartSensor Rail learn more link on Products page
- [ ] Links to dealer websites on Contact Us page

**Comment by conterio** [comment]
Do we know what links these are?

**Comment by partydrone** [comment]
There's a link on the products page for SmartSensor Rail to a dealer website. Also, when listing dealers on the Contact Us page, links to their websites should also open in a new tab or window.

I updated the description of this issue to include those items.
