### ISSUE TITLE
Articles By Topic - Tag Bug

### ISSUE THREAD

**Issue by ZRichins** [wavetronix/glados#138]
I was clicking the tag 'hd' in the topics list on the about us page and got an error. 
![screenshot 2017-05-02 17 13 55](https://cloud.githubusercontent.com/assets/11444985/25643105/f9229cfc-2f5a-11e7-8b2d-f0f95f733e14.png)

**Comment by partydrone** [comment]
It looks like this happens when an article is tagged, then deleted. The corresponding tagging in the database remains. Then, when looking for everything tagged with a certain tag, there are `nil` responses the show up in the results.

**Comment by partydrone** [comment]
The cause of this issue is the same as #107.
