### ISSUE TITLE
Missing Support Link

### ISSUE THREAD

**Issue by ZRichins** [wavetronix/glados#164]
The support link is suddenly missing from the top of the SmartSensor V page.
![screenshot 2017-05-11 16 21 22](https://cloud.githubusercontent.com/assets/11444985/25974360/f1507bae-3665-11e7-9444-4f8755070011.png)

**Comment by ZRichins** [comment]
And the Advance, Advance Extended Range and Matrix pages.

**Comment by partydrone** [comment]
This is intentional behavior when there is no content for that section.
