### ISSUE TITLE
Error when trying to edit/updating product

### ISSUE THREAD

**Issue by conterio** [wavetronix/glados#176]
1. go to the admin page
2. open up products
3. edit a product and try to update

![image](https://cloud.githubusercontent.com/assets/10100453/26269887/c51ba180-3cb4-11e7-9abe-d33d03967f83.png)
![image](https://cloud.githubusercontent.com/assets/10100453/26269897/d94d42e4-3cb4-11e7-85e6-a33bf0ddfcea.png)

**Comment by partydrone** [comment]
This is the same as #175 opened by @ehuntsman.
