### ISSUE TITLE
"Request a demo" button on home page does nothing

### ISSUE THREAD

**Issue by partydrone** [wavetronix/glados#194]
## Expected Behavior
Display a form or something.

## Actual Behavior
Nothing.

## Steps to Reproduce the Problem

  1. Go to home page
  1. Click "Request a demo" button

**Comment by conterio** [comment]
@partydrone what should the form have on it? name, email, phone, etc?  also should this just be like a modal popup or should it redirect them to a seperate page?

**Comment by partydrone** [comment]
All good questions. If you take this on, work with @ehuntsman and Zac.
