### ISSUE TITLE
Support Page

### ISSUE THREAD

**Issue by ZRichins** [wavetronix/glados#243]
Change request.

Could we change the wording and order of buttons on the support page? Specifically in the knowledge base section? 

The current text refers to not finding your answer (which made more sense when we were doing an FAQ) but now we're not. Also, putting the link before the search would be nice. I've attached some screens to illustrate what I'm talking about.

Thanks.

![support copy 2 2x](https://cloud.githubusercontent.com/assets/11444985/26804348/e1951f96-4a04-11e7-8b89-3132f9a09b3c.png)
![support iphone copy 2x](https://cloud.githubusercontent.com/assets/11444985/26804357/e9c4336e-4a04-11e7-97e7-a6122edaa4ee.png)
![support tablet copy 2x](https://cloud.githubusercontent.com/assets/11444985/26804371/f56c2366-4a04-11e7-8448-fcbc7fea2ebc.png)

**Comment by partydrone** [comment]
In conversations with Jimmy and Emily, there is a deep concern about the browsing experience users will have.

As things are implemented right now, _searching_ the knowledge base provides the best user experience, I think. Considering that, I think it's better to leave the search box _above_ the browse link to promote that interaction.

I do think it's a good idea, though, to change the label on the button to follow the _verb, noun_ convention used on all the other buttons on the page ("Visit App Support", "View Return Policy", "Browse Knowledge Base"). How does that sound?

**Comment by ZRichins** [comment]
Sounds great. Thanks for your help and insight.


On Jun 6, 2017, at 4:22 PM, Andrew Porter <notifications@github.com<mailto:notifications@github.com>> wrote:


In conversations with Jimmy and Emily, there is a deep concern about the browsing experience users will have.

As things are implemented right now, searching the knowledge base provides the best user experience, I think. Considering that, I think it's better to leave the search box above the browse link to promote that interaction.

I do think it's a good idea, though, to change the label on the button to follow the verb, noun convention used on all the other buttons on the page ("Visit App Support", "View Return Policy", "Browse Knowledge Base"). How does that sound?
