### ISSUE TITLE
Separate blog out of 'about us' to main navigation

### ISSUE THREAD

**Issue by ZRichins** [wavetronix/glados#271]
## Expected Behavior
Currently the news/blog articles are found under the 'about us' section. The desire to move this to its own section has been expressed. 

## Actual Behavior
The top navigation would now list blog as the last link (after about us).

Attached are some screens to show the changes to both the "about us" and "blog" pages.

![pulse-blog](https://user-images.githubusercontent.com/11444985/29882603-c8013930-8d6a-11e7-88a2-c8ecadae5a6d.png)
![about us](https://user-images.githubusercontent.com/11444985/29882604-c81f8df4-8d6a-11e7-89b1-d8b8e3fd50fc.png)

**Comment by partydrone** [comment]
Very good. Having a single-word label up there with all those active phrases feels out of place. Do you want to come up with another active phrase for the blog, or do you think we should condense everything down to short labels:

- Products
- Support
- Training
- Contact Us
- About Us
- Blog

**Comment by ZRichins** [comment]
We discussed this and decided we’re okay with blog being just blog and leaving the rest.

Zac Richins

Interaction Designer
Wavetronix

On Aug 31, 2017, at 11:05 AM, Andrew Porter <notifications@github.com<mailto:notifications@github.com>> wrote:


Very good. Having a single-word label up there with all those active phrases feels out of place. Do you want to come up with another active phrase for the blog, or do you think we should condense everything down to short labels:

  *   Products
  *   Support
  *   Training
  *   Contact Us
  *   About Us
  *   Blog

**Comment by partydrone** [comment]
Whatever we do, we need to be consistent. How does "Read News" sound?

Also, I think it's a good idea to use "news" instead of "blog". After looking around at some other big players like Adobe, Apple, Microsoft, even Econolite and Sensys, they all use the term "news". It sounds more legit, and "blog" sounds like we're an independent, less-legit organization.

**Comment by ZRichins** [comment]
I double checked, again, with Don and Steve and this is what I was told. 

Steve really wanted _Blog_ for its informal connotations but Don feels that _News_ is more appropriate. In the end this is what was decided. We'd like it to say _Pulse News_. We know it's not a call to action/verb but it comes directly after _About Us_ which ins't a call to action/verb already. I've attached an updated version:

![all news events 2x](https://user-images.githubusercontent.com/11444985/30761428-7416da08-9f9b-11e7-9562-07278c0d1c45.png)

**Comment by ZRichins** [comment]
Based on further research and consideration we've decided to withdraw this request.
