### ISSUE TITLE
Contact us

### ISSUE THREAD

**Issue by partydrone** [wavetronix/glados#64]
Provide contact options and information to site visitors.

---

Acceptance criteria:
- [x] Search for dealer by state/province
- [x] Search for dealer by country
- [x] Search for dealer by name
- [x] Display all possible dealers
- [x] Display all possible sales offices
- [x] List Wavetronix offices
- [x] Link to company social media pages
- [x] Display public relations info
- [x] Submit website feedback

**Comment by ehuntsman** [comment]
Marketing isn't sure why "Display all possible dealers" is on the list. I left it on so we can discuss in a future meeting.
